# .github/workflows/docker-build.yml
name: Build and Dockerize ML App with GCS Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MODEL_PATH: ${{ secrets.MODEL_URI }}
      MODEL_LOCAL_DIR: src
      MODEL_FILENAME: roberta-sequence-classification-9.onnx.onnx

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          install_components: 'gcloud'

      - name: Make model directory
        run: mkdir -p $MODEL_LOCAL_DIR

      - name: Download model from GCS
        run: |
          gcloud storage cp $MODEL_PATH $MODEL_LOCAL_DIR/$MODEL_FILENAME

      - name: Build Docker image
        run: |
          make build

      # Optional: Push to Docker Hub or GCR
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image
        run: make push
